import os
import pathlib
import sys
from typing import List, Optional, Tuple

from .config import get_build_dir
from .registry import get_registry


_SHELL_INIT_TEMPLATE = r"""# hepyy shell integration — generated by `hepyy shell-init`
# Add to ~/.bashrc or ~/.zshrc:  eval "$(hepyy shell-init)"

module() {
  local action="$1"
  local pkg="$2"
  local name="${pkg%%/*}"
  local version="${pkg#*/}"
  [ "$version" = "$name" ] && version=""

  case "$action" in
    load)
      local env_path
      env_path="$(hepyy _shell-env-path "$name" $version 2>/dev/null)" || {
        echo "hepyy: package '$pkg' not found" >&2
        return 1
      }
      # shellcheck disable=SC1090
      source "$env_path/env.sh"
      ;;
    unload)
      local env_path
      env_path="$(hepyy _shell-env-path "$name" $version 2>/dev/null)" || {
        echo "hepyy: package '$pkg' not found" >&2
        return 1
      }
      # shellcheck disable=SC1090
      source "$env_path/env-unset.sh"
      ;;
    list)
      hepyy _shell-list
      ;;
    avail)
      hepyy avail
      ;;
    *)
      echo "Usage: module {load|unload|list|avail} [package[/version]]" >&2
      return 1
      ;;
  esac
}

# --- auto-wire completion + 'module use <modulefiles>' on venv/conda entry ---
# One-time, per-machine hook (added once to ~/.bashrc or ~/.zshrc). It does
# nothing until you activate a venv/conda env that has heyy installed, and it
# correctly does nothing again after 'pip uninstall hepyy' — there is no
# per-env file to clean up. Re-checks on every prompt since neither bash nor
# zsh has a native "env activated" event.
_heyy_env_watch() {
  local cur="${VIRTUAL_ENV:-}:${CONDA_PREFIX:-}"
  if [ "$cur" != "${_HEYY_LAST_ENV:-}" ]; then
    _HEYY_LAST_ENV="$cur"
    if command -v heyy >/dev/null 2>&1; then
      eval "$(heyy completion 2>/dev/null)"
      # Only wire 'module use <dir>' into a REAL Lmod/Environment Modules
      # 'module' command. heyy's own module() shim (defined above) manages
      # heyy packages directly via 'module load <pkg>/<ver>' and has no
      # 'use' action — eval'ing this against the shim would just print
      # "Usage: module {load|unload|list|avail} ..." on every env switch.
      if [ -n "${LMOD_CMD:-}${MODULESHOME:-}" ]; then
        eval "$(heyy modules 2>/dev/null)"
      fi
    else
      # Left an env that had heyy — drop the now-dead completion registration
      # rather than leaving it pointing at a command no longer on PATH.
      if [ -n "${ZSH_VERSION:-}" ]; then
        compdef -d heyy her hepyy 2>/dev/null
      else
        complete -r heyy her hepyy 2>/dev/null
      fi
    fi
  fi
}

if [ -n "${ZSH_VERSION:-}" ]; then
  autoload -Uz add-zsh-hook 2>/dev/null
  if command -v add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook precmd _heyy_env_watch
  else
    precmd_functions+=(_heyy_env_watch)
  fi
elif [ -n "${BASH_VERSION:-}" ]; then
  case ";${PROMPT_COMMAND:-};" in
    *";_heyy_env_watch;"*) ;;
    *) PROMPT_COMMAND="_heyy_env_watch${PROMPT_COMMAND:+;$PROMPT_COMMAND}" ;;
  esac
fi
"""


_SHELL_INIT_FISH_TEMPLATE = r"""# hepyy shell integration — generated by `hepyy shell-init --shell fish`
# Add to ~/.config/fish/config.fish:  hepyy shell-init --shell fish | source

# fish has a native "variable changed" event, so no polling is needed here:
# this fires exactly on venv/conda activation and deactivation. It does
# nothing when heyy isn't on PATH (plain env, or after 'pip uninstall hepyy').
function _heyy_env_watch --on-variable VIRTUAL_ENV --on-variable CONDA_PREFIX
    if command -v heyy >/dev/null 2>&1
        heyy completion --shell fish | source
        # Only wire 'module use <dir>' when a real Lmod/Environment Modules
        # 'module' command is actually present — otherwise there's nothing
        # for 'module use' to configure and it would just fail as unknown.
        if set -q LMOD_CMD; or set -q MODULESHOME
            eval (heyy modules 2>/dev/null)
        end
    end
end
"""



def shell_init_script(shell: str = "bash") -> str:
    if shell == "fish":
        return _SHELL_INIT_FISH_TEMPLATE
    return _SHELL_INIT_TEMPLATE


def get_modulefiles_dir() -> pathlib.Path:
    return get_build_dir() / "modulefiles"


def write_tcl_modulefile(name: str, version: str, prefix: pathlib.Path, python_paths=None, depends_on=None) -> pathlib.Path:
    """Generate a TCL modulefile for use with Environment Modules / Lmod."""
    NAME = name.upper().replace("-", "_")
    p = prefix
    lines = [
        "#%Module1.0",
        f"## {name}/{version} — generated by hepyy",
        "",
        f'module-whatis "{name} {version}"',
        "",
    ]
    # Load dependencies first so 'module load hepbundle' cascades to all members.
    for dep in (depends_on or []):
        lines.append(f"module load {dep}")
    if depends_on:
        lines.append("")
    lines += [
        f"set prefix {p}",
        "",
        f"setenv {NAME}_DIR $prefix",
        f"setenv {NAME}_VERSION {version}",
        f"setenv HEPYY_LOADED_{NAME} {version}",
        f"setenv HEPYY_LOADED_{NAME}_PREFIX $prefix",
    ]
    if (p / "bin").is_dir():
        lines.append("prepend-path PATH $prefix/bin")
    _lib_dir = p / "lib" if (p / "lib").is_dir() else (p / "lib64" if (p / "lib64").is_dir() else None)
    if _lib_dir is not None:
        _lib_rel = _lib_dir.relative_to(p)
        lines.append(f"prepend-path LD_LIBRARY_PATH $prefix/{_lib_rel}")
        lines.append(f"prepend-path DYLD_LIBRARY_PATH $prefix/{_lib_rel}")
        for sp in sorted(_lib_dir.glob("python*/site-packages")):
            rel = sp.relative_to(p)
            lines.append(f"prepend-path PYTHONPATH $prefix/{rel}")
    # Explicit python_paths from recipe (e.g. "." for --target installs, "lib" for ROOT).
    # These are in addition to the lib/python*/site-packages glob above.
    for rel in (python_paths or []):
        entry = "prepend-path PYTHONPATH $prefix" if rel == "." else f"prepend-path PYTHONPATH $prefix/{rel}"
        if entry not in lines:
            lines.append(entry)
    if (p / "include").is_dir():
        lines.append("prepend-path CPATH $prefix/include")
    content = "\n".join(lines) + "\n"

    mod_dir = get_modulefiles_dir() / name
    mod_dir.mkdir(parents=True, exist_ok=True)
    mod_file = mod_dir / version
    mod_file.write_text(content)
    return mod_file


def generate_env_scripts(name: str, version: str, prefix: pathlib.Path, python_paths=None) -> None:
    NAME = name.upper().replace("-", "_")
    prefix_str = str(prefix)

    _lib_path = (
        prefix / "lib" if (prefix / "lib").is_dir()
        else (prefix / "lib64" if (prefix / "lib64").is_dir() else prefix / "lib")
    )
    lib_dir = str(_lib_path)
    bin_dir = f"{prefix_str}/bin"
    inc_dir = f"{prefix_str}/include"
    lib_var = "DYLD_LIBRARY_PATH" if sys.platform == "darwin" else "LD_LIBRARY_PATH"

    # Collect PYTHONPATH entries: glob fallback + explicit python_paths
    py_dirs: list = []
    for sp in sorted(_lib_path.glob("python*/site-packages")):
        py_dirs.append(str(sp))
    for rel in (python_paths or []):
        d = prefix_str if rel == "." else str(prefix / rel)
        if d not in py_dirs:
            py_dirs.append(d)

    def _esc(s: str) -> str:
        return s.replace("/", "\\/")

    # env.sh
    set_lines = [
        f"# hepyy env — {name} {version}",
        f'export {NAME}_DIR="{prefix_str}"',
        f'export PATH="{bin_dir}:$PATH"',
        f'export {lib_var}="{lib_dir}:${lib_var}"',
    ]
    for d in py_dirs:
        set_lines.append(f'export PYTHONPATH="{d}:$PYTHONPATH"')

    # CPyCppyy API headers: pip '--target' installs land at
    #   {prefix}/include/site/python*/CPyCppyy/
    # Export CPPYY_API_PATH so that a bare `import cppyy` in user code (before
    # hepyy.load is called) initialises cppyy's string_meta correctly.
    import glob as _glob_sh
    _cpycppyy_cands = _glob_sh.glob(
        str(prefix / 'include' / 'site' / 'python*' / 'CPyCppyy')
    )
    _cpycppyy_api = _cpycppyy_cands[0] if _cpycppyy_cands else None

    if _cpycppyy_api:
        set_lines.append(f'export CPPYY_API_PATH="{_cpycppyy_api}"')

    set_lines += [
        f'export CPATH="{inc_dir}:$CPATH"',
        f'export HEPYY_LOADED_{NAME}="{version}"',
        f'export HEPYY_LOADED_{NAME}_PREFIX="{prefix_str}"',
    ]

    # env-unset.sh
    unset_lines = [
        f"# hepyy env-unset — {name} {version}",
        f'export PATH="${{PATH//{_esc(bin_dir)}:/}}"',
        f'export {lib_var}="${{{lib_var}//{_esc(lib_dir)}:/}}"',
    ]
    for d in py_dirs:
        unset_lines.append(f'export PYTHONPATH="${{PYTHONPATH//{_esc(d)}:/}}"')
    if _cpycppyy_api:
        unset_lines.append('unset CPPYY_API_PATH')
    unset_lines += [
        f'export CPATH="${{CPATH//{_esc(inc_dir)}:/}}"',
        f"unset {NAME}_DIR",
        f"unset HEPYY_LOADED_{NAME}",
        f"unset HEPYY_LOADED_{NAME}_PREFIX",
    ]

    (prefix / "env.sh").write_text("\n".join(set_lines) + "\n")
    (prefix / "env-unset.sh").write_text("\n".join(unset_lines) + "\n")


def env_path(name: str, version: Optional[str] = None) -> pathlib.Path:
    reg = get_registry()
    record = reg.get(name)
    if record is None:
        from .exceptions import PackageNotInstalledError
        raise PackageNotInstalledError(
            f"Package '{name}' is not installed. Run: hepyy install {name}"
        )
    if version and record.get("version") != version:
        # Try to find that version directly in build dir
        candidate = get_build_dir() / name / version
        if (candidate / "env.sh").exists():
            return candidate
        from .exceptions import PackageNotInstalledError
        raise PackageNotInstalledError(
            f"Package '{name}' version '{version}' not found. "
            f"Installed: {record.get('version')}"
        )
    return pathlib.Path(record["prefix"])


def list_loaded() -> List[Tuple[str, str]]:
    results = []
    for key, value in os.environ.items():
        if key.startswith("HEPYY_LOADED_") and not key.endswith("_PREFIX"):
            name = key[len("HEPYY_LOADED_"):].lower().replace("_", "-")
            results.append((name, value))
    return results


def write_sitecustomize() -> pathlib.Path:
    """Write hepyy_autoload.pth to the active venv's site-packages.

    site.py processes .pth files before importing sitecustomize, so this works
    even when a system-level sitecustomize.py (e.g. Homebrew's) shadows ours.
    The .pth file imports hepyy._autoload which calls hepyy.load() for
    every package whose HEPYY_LOADED_* env var is set by 'module load'.
    """
    import sysconfig
    site_dir = pathlib.Path(sysconfig.get_paths()["purelib"])
    site_dir.mkdir(parents=True, exist_ok=True)

    # Remove old sitecustomize.py if we wrote it previously
    old = site_dir / "sitecustomize.py"
    if old.exists() and "hepyy" in old.read_text():
        old.unlink()

    # Remove stale .pth from the pre-rename package (heppyyier → hepyy)
    stale_pth = site_dir / "heppyyier_autoload.pth"
    if stale_pth.exists():
        stale_pth.unlink()

    dest = site_dir / "hepyy_autoload.pth"
    dest.write_text("import hepyy._autoload\n")
    return dest
